[2023-08-22T20:19:50.936+0000] {processor.py:154} INFO - Started process (PID=8822) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:19:50.937+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:19:50.938+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:19:50.938+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:19:50.957+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:19:50.973+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.040 seconds
[2023-08-22T20:20:21.947+0000] {processor.py:154} INFO - Started process (PID=8886) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:21.948+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:21.949+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:21.949+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:21.961+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:21.976+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.032 seconds
[2023-08-22T20:20:29.789+0000] {processor.py:154} INFO - Started process (PID=8927) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:29.790+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:29.791+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:29.791+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:29.817+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:29.831+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-08-22T20:20:31.152+0000] {processor.py:154} INFO - Started process (PID=8933) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:31.153+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:31.154+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:31.154+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:31.175+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:31.173+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 2
    from
        ^
SyntaxError: invalid syntax
[2023-08-22T20:20:31.176+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:31.199+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.052 seconds
[2023-08-22T20:20:35.256+0000] {processor.py:154} INFO - Started process (PID=8934) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:35.257+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:35.258+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:35.258+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:35.284+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:35.283+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 2
    from datetime
                ^
SyntaxError: invalid syntax
[2023-08-22T20:20:35.285+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:35.305+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.053 seconds
[2023-08-22T20:20:39.355+0000] {processor.py:154} INFO - Started process (PID=8944) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:39.356+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:39.357+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:39.356+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:39.381+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:39.399+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2023-08-22T20:20:41.370+0000] {processor.py:154} INFO - Started process (PID=8945) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:41.371+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:41.372+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:41.372+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:41.401+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:41.417+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.050 seconds
[2023-08-22T20:20:44.392+0000] {processor.py:154} INFO - Started process (PID=8946) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:44.393+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:44.394+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:44.394+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:44.422+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:44.419+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    W
NameError: name 'W' is not defined
[2023-08-22T20:20:44.424+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:44.447+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.058 seconds
[2023-08-22T20:20:47.473+0000] {processor.py:154} INFO - Started process (PID=8947) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:47.474+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:47.475+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:47.475+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:47.496+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:47.495+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG
           ^
SyntaxError: invalid syntax
[2023-08-22T20:20:47.497+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:47.516+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-08-22T20:20:49.502+0000] {processor.py:154} INFO - Started process (PID=8957) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:49.503+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:49.504+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:49.504+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:49.521+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:49.521+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG()
             ^
SyntaxError: invalid syntax
[2023-08-22T20:20:49.522+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:49.544+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-08-22T20:20:53.582+0000] {processor.py:154} INFO - Started process (PID=8958) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:53.583+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:53.584+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:53.584+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:53.604+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:53.602+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user')
                   ^
SyntaxError: invalid syntax
[2023-08-22T20:20:53.604+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:53.649+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.071 seconds
[2023-08-22T20:20:55.304+0000] {processor.py:154} INFO - Started process (PID=8968) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:55.305+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:55.306+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:55.306+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:55.323+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:55.322+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_pro')
                       ^
SyntaxError: invalid syntax
[2023-08-22T20:20:55.324+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:55.344+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.044 seconds
[2023-08-22T20:20:56.344+0000] {processor.py:154} INFO - Started process (PID=8980) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:56.345+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:56.346+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:56.346+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:56.364+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:56.363+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_proc')
                        ^
SyntaxError: invalid syntax
[2023-08-22T20:20:56.365+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:56.386+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-08-22T20:20:59.489+0000] {processor.py:154} INFO - Started process (PID=9001) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:59.490+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:20:59.491+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:59.491+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:59.513+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:20:59.512+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing')
                              ^
SyntaxError: invalid syntax
[2023-08-22T20:20:59.514+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:20:59.536+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.050 seconds
[2023-08-22T20:21:08.934+0000] {processor.py:154} INFO - Started process (PID=9007) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:08.935+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:08.936+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:08.936+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:08.956+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:08.955+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start)
                                     ^
SyntaxError: invalid syntax
[2023-08-22T20:21:08.957+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:09.006+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.075 seconds
[2023-08-22T20:21:12.978+0000] {processor.py:154} INFO - Started process (PID=9017) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:12.979+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:12.980+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:12.979+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:12.997+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:12.996+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date)
                                          ^
SyntaxError: invalid syntax
[2023-08-22T20:21:12.997+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:13.018+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.044 seconds
[2023-08-22T20:21:14.993+0000] {processor.py:154} INFO - Started process (PID=9018) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:14.995+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:14.996+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:14.995+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:15.014+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:15.014+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date=)
                                           ^
SyntaxError: invalid syntax
[2023-08-22T20:21:15.015+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:15.036+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.047 seconds
[2023-08-22T20:21:19.080+0000] {processor.py:154} INFO - Started process (PID=9019) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:19.081+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:19.081+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:19.081+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:19.106+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:19.105+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime)
                                                     ^
SyntaxError: invalid syntax
[2023-08-22T20:21:19.107+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:19.127+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.050 seconds
[2023-08-22T20:21:22.112+0000] {processor.py:154} INFO - Started process (PID=9029) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:22.114+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:22.115+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:22.114+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:22.136+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:22.135+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2))
                                                        ^
SyntaxError: invalid syntax
[2023-08-22T20:21:22.137+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:22.161+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.051 seconds
[2023-08-22T20:21:24.135+0000] {processor.py:154} INFO - Started process (PID=9030) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:24.136+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:24.137+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:24.137+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:24.158+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:24.157+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023))
                                                           ^
SyntaxError: invalid syntax
[2023-08-22T20:21:24.158+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:24.180+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2023-08-22T20:21:25.942+0000] {processor.py:154} INFO - Started process (PID=9039) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:25.943+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:25.944+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:25.943+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:25.961+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:25.960+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023,))
                                                            ^
SyntaxError: invalid syntax
[2023-08-22T20:21:25.962+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:25.983+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.045 seconds
[2023-08-22T20:21:27.395+0000] {processor.py:154} INFO - Started process (PID=9058) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:27.396+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:27.397+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:27.397+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:27.418+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:27.417+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023,8,))
                                                              ^
SyntaxError: invalid syntax
[2023-08-22T20:21:27.419+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:27.438+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-08-22T20:21:29.825+0000] {processor.py:154} INFO - Started process (PID=9064) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:29.826+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:29.827+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:29.827+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:29.849+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:29.847+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8,))
                                                               ^
SyntaxError: invalid syntax
[2023-08-22T20:21:29.850+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:29.870+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2023-08-22T20:21:31.843+0000] {processor.py:154} INFO - Started process (PID=9065) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:31.844+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:31.844+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:31.844+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:31.863+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:31.862+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, ))
                                                                ^
SyntaxError: invalid syntax
[2023-08-22T20:21:31.864+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:31.886+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2023-08-22T20:21:37.277+0000] {processor.py:154} INFO - Started process (PID=9080) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:37.278+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:21:37.279+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:37.279+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:37.299+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:21:37.298+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23))
                                                                  ^
SyntaxError: invalid syntax
[2023-08-22T20:21:37.299+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:21:37.322+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2023-08-22T20:22:07.420+0000] {processor.py:154} INFO - Started process (PID=9144) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:07.421+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:22:07.422+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:07.422+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:07.437+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:07.436+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23))
                                                                  ^
SyntaxError: invalid syntax
[2023-08-22T20:22:07.437+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:07.460+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.044 seconds
[2023-08-22T20:22:36.010+0000] {processor.py:154} INFO - Started process (PID=9199) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:36.012+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:22:36.013+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:36.012+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:36.030+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:36.029+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:22:36.030+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:36.051+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.043 seconds
[2023-08-22T20:22:38.069+0000] {processor.py:154} INFO - Started process (PID=9200) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:38.070+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:22:38.072+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:38.071+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:38.088+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:38.086+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:22:38.088+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:38.110+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.044 seconds
[2023-08-22T20:22:40.101+0000] {processor.py:154} INFO - Started process (PID=9208) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:40.102+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:22:40.103+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:40.103+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:40.123+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:40.122+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:22:40.124+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:40.150+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.052 seconds
[2023-08-22T20:22:43.162+0000] {processor.py:154} INFO - Started process (PID=9211) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:43.163+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:22:43.164+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:43.164+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:43.185+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:43.184+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:22:43.186+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:43.206+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.047 seconds
[2023-08-22T20:22:47.218+0000] {processor.py:154} INFO - Started process (PID=9212) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:47.219+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:22:47.220+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:47.220+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:47.240+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:47.239+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:22:47.241+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:47.263+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2023-08-22T20:22:50.274+0000] {processor.py:154} INFO - Started process (PID=9213) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:50.275+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:22:50.276+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:50.276+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:50.293+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:50.292+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:22:50.293+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:50.312+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.041 seconds
[2023-08-22T20:22:51.318+0000] {processor.py:154} INFO - Started process (PID=9220) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:51.319+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:22:51.320+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:51.320+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:51.340+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:51.339+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:22:51.341+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:51.366+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.054 seconds
[2023-08-22T20:22:54.361+0000] {processor.py:154} INFO - Started process (PID=9224) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:54.362+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:22:54.363+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:54.363+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:54.382+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:54.381+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:22:54.383+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:54.403+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-08-22T20:22:55.415+0000] {processor.py:154} INFO - Started process (PID=9225) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:55.415+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:22:55.416+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:55.416+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:55.440+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:22:55.439+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:22:55.440+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:22:55.462+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.051 seconds
[2023-08-22T20:23:26.436+0000] {processor.py:154} INFO - Started process (PID=9289) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:26.437+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:23:26.438+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:23:26.438+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:26.452+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:23:26.451+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:23:26.453+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:26.476+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.045 seconds
[2023-08-22T20:23:45.393+0000] {processor.py:154} INFO - Started process (PID=9335) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:45.395+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:23:45.396+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:23:45.395+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:45.416+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:23:45.415+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:23:45.417+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:45.443+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.052 seconds
[2023-08-22T20:23:48.439+0000] {processor.py:154} INFO - Started process (PID=9345) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:48.440+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:23:48.441+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:23:48.441+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:48.461+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:23:48.460+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:23:48.461+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:48.482+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.047 seconds
[2023-08-22T20:23:50.498+0000] {processor.py:154} INFO - Started process (PID=9346) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:50.499+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:23:50.500+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:23:50.500+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:50.519+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:23:50.518+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23)),
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:23:50.519+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:50.540+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.045 seconds
[2023-08-22T20:23:59.438+0000] {processor.py:154} INFO - Started process (PID=9368) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:59.439+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:23:59.440+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:23:59.440+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:59.459+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:23:59.459+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    schedule_interval = '@daily',
                                 ^
SyntaxError: unexpected EOF while parsing
[2023-08-22T20:23:59.460+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:23:59.485+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.050 seconds
[2023-08-22T20:24:04.293+0000] {processor.py:154} INFO - Started process (PID=9388) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:04.295+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:04.296+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:04.296+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:04.317+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:04.316+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 7
    schedule_interval = '@daily',
                                 ^
SyntaxError: unexpected EOF while parsing
[2023-08-22T20:24:04.318+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:04.342+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.052 seconds
[2023-08-22T20:24:09.811+0000] {processor.py:154} INFO - Started process (PID=9394) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:09.813+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:09.814+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:09.814+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:09.832+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:09.831+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 7
    ,
    ^
SyntaxError: invalid syntax
[2023-08-22T20:24:09.833+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:09.853+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.045 seconds
[2023-08-22T20:24:11.874+0000] {processor.py:154} INFO - Started process (PID=9404) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:11.874+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:11.875+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:11.875+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:11.895+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:11.894+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 7
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-08-22T20:24:11.895+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:11.920+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2023-08-22T20:24:14.962+0000] {processor.py:154} INFO - Started process (PID=9405) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:14.964+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:14.964+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:14.964+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:14.984+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:14.983+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    with DAG('user_processing', start_date = datetime(2023, 8, 23),)
                                                                   ^
SyntaxError: invalid syntax
[2023-08-22T20:24:14.985+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:15.006+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2023-08-22T20:24:16.980+0000] {processor.py:154} INFO - Started process (PID=9406) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:16.981+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:16.982+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:16.982+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:17.003+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:17.002+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    )
    ^
SyntaxError: invalid syntax
[2023-08-22T20:24:17.003+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:17.024+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2023-08-22T20:24:18.051+0000] {processor.py:154} INFO - Started process (PID=9407) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:18.052+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:18.053+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:18.053+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:18.072+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:18.071+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    schedule_interval = '@daily')
                                ^
SyntaxError: invalid syntax
[2023-08-22T20:24:18.073+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:18.096+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2023-08-22T20:24:22.148+0000] {processor.py:154} INFO - Started process (PID=9417) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:22.150+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:22.151+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:22.151+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:22.173+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:22.172+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    schedule_interval = '@daily', )
                                  ^
SyntaxError: invalid syntax
[2023-08-22T20:24:22.173+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:22.199+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.055 seconds
[2023-08-22T20:24:33.807+0000] {processor.py:154} INFO - Started process (PID=9458) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:33.808+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:33.809+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:33.809+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:33.829+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:33.828+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    schedule_interval = '@daily', catch)
                                       ^
SyntaxError: invalid syntax
[2023-08-22T20:24:33.830+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:33.850+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-08-22T20:24:36.876+0000] {processor.py:154} INFO - Started process (PID=9459) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:36.877+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:36.878+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:36.878+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:36.897+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:36.896+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    schedule_interval = '@daily', catchup)
                                         ^
SyntaxError: invalid syntax
[2023-08-22T20:24:36.897+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:36.919+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-08-22T20:24:41.301+0000] {processor.py:154} INFO - Started process (PID=9465) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:41.302+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:41.303+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:41.303+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:41.320+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:41.319+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    schedule_interval = '@daily', catchup = False)
                                                 ^
SyntaxError: invalid syntax
[2023-08-22T20:24:41.320+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:41.339+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.041 seconds
[2023-08-22T20:24:43.355+0000] {processor.py:154} INFO - Started process (PID=9466) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:43.356+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:43.358+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:43.357+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:43.378+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:43.377+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    schedule_interval = '@daily', catchup = False) AS
                                                    ^
SyntaxError: invalid syntax
[2023-08-22T20:24:43.379+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:43.401+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2023-08-22T20:24:45.393+0000] {processor.py:154} INFO - Started process (PID=9476) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:45.394+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:45.395+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:45.395+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:45.415+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:45.414+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    schedule_interval = '@daily', catchup = False) as
                                                     ^
SyntaxError: invalid syntax
[2023-08-22T20:24:45.416+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:45.435+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-08-22T20:24:48.459+0000] {processor.py:154} INFO - Started process (PID=9477) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:48.460+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:48.461+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:48.461+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:48.480+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:48.479+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-08-22T20:24:48.481+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:48.501+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.044 seconds
[2023-08-22T20:24:49.483+0000] {processor.py:154} INFO - Started process (PID=9478) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:49.484+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:49.485+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:49.485+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:49.501+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:49.500+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 9
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-08-22T20:24:49.503+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:49.523+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.044 seconds
[2023-08-22T20:24:57.612+0000] {processor.py:154} INFO - Started process (PID=9488) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:57.613+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:57.614+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:57.614+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:57.634+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:57.633+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-08-22T20:24:57.635+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:57.655+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.047 seconds
[2023-08-22T20:24:58.922+0000] {processor.py:154} INFO - Started process (PID=9494) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:58.924+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:24:58.925+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:58.925+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:58.960+0000] {processor.py:766} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:24:59.183+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:59.183+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:user_processing
[2023-08-22T20:24:59.195+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:59.195+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:user_processing
[2023-08-22T20:24:59.205+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:59.205+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:user_processing
[2023-08-22T20:24:59.206+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:59.206+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-08-22T20:24:59.218+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:59.218+0000] {dag.py:2606} INFO - Creating ORM DAG for user_processing
[2023-08-22T20:24:59.230+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:24:59.230+0000] {dag.py:3340} INFO - Setting next_dagrun for user_processing to 2023-08-23T00:00:00+00:00, run_after=2023-08-24T00:00:00+00:00
[2023-08-22T20:24:59.255+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.336 seconds
[2023-08-22T20:25:29.525+0000] {processor.py:154} INFO - Started process (PID=9557) to work on /opt/airflow/dags/user_processing.py
[2023-08-22T20:25:29.526+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-08-22T20:25:29.527+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:25:29.527+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-08-22T20:25:29.588+0000] {processor.py:766} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2023-08-22T20:25:29.641+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:25:29.641+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-08-22T20:25:29.682+0000] {logging_mixin.py:120} INFO - [2023-08-22T20:25:29.682+0000] {dag.py:3340} INFO - Setting next_dagrun for user_processing to 2023-08-23T00:00:00+00:00, run_after=2023-08-24T00:00:00+00:00
[2023-08-22T20:25:29.711+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.190 seconds
