[2023-09-05T18:59:37.199+0000] {processor.py:154} INFO - Started process (PID=22727) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T18:59:37.199+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T18:59:37.200+0000] {logging_mixin.py:120} INFO - [2023-09-05T18:59:37.200+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T18:59:37.236+0000] {logging_mixin.py:120} INFO - [2023-09-05T18:59:37.230+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T18:59:37.238+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T18:59:37.261+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.064 seconds
[2023-09-05T19:00:07.948+0000] {processor.py:154} INFO - Started process (PID=22793) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:00:07.949+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:00:07.950+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:00:07.950+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:00:07.967+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:00:07.963+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:00:07.968+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:00:07.985+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.039 seconds
[2023-09-05T19:00:38.693+0000] {processor.py:154} INFO - Started process (PID=22868) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:00:38.694+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:00:38.694+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:00:38.694+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:00:38.712+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:00:38.709+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:00:38.714+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:00:38.730+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.040 seconds
[2023-09-05T19:01:09.385+0000] {processor.py:154} INFO - Started process (PID=22946) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:01:09.386+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:01:09.387+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:01:09.387+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:01:09.405+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:01:09.401+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:01:09.407+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:01:09.424+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.041 seconds
[2023-09-05T19:01:40.055+0000] {processor.py:154} INFO - Started process (PID=23024) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:01:40.056+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:01:40.056+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:01:40.056+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:01:40.073+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:01:40.070+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:01:40.075+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:01:40.095+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.043 seconds
[2023-09-05T19:02:10.815+0000] {processor.py:154} INFO - Started process (PID=23090) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:02:10.816+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:02:10.817+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:02:10.817+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:02:10.833+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:02:10.830+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:02:10.835+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:02:10.853+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.041 seconds
[2023-09-05T19:02:41.483+0000] {processor.py:154} INFO - Started process (PID=23164) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:02:41.484+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:02:41.484+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:02:41.484+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:02:41.502+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:02:41.498+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:02:41.503+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:02:41.522+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:03:12.309+0000] {processor.py:154} INFO - Started process (PID=23242) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:03:12.310+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:03:12.311+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:03:12.311+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:03:12.330+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:03:12.326+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:03:12.332+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:03:12.352+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:03:43.010+0000] {processor.py:154} INFO - Started process (PID=23316) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:03:43.011+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:03:43.011+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:03:43.011+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:03:43.029+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:03:43.026+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:03:43.030+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:03:43.048+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.041 seconds
[2023-09-05T19:04:13.085+0000] {processor.py:154} INFO - Started process (PID=23381) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:04:13.086+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:04:13.087+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:04:13.087+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:04:13.105+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:04:13.101+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:04:13.106+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:04:13.124+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:04:43.515+0000] {processor.py:154} INFO - Started process (PID=23455) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:04:43.517+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:04:43.518+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:04:43.518+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:04:43.541+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:04:43.535+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:04:43.544+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:04:43.564+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.052 seconds
[2023-09-05T19:05:13.702+0000] {processor.py:154} INFO - Started process (PID=23529) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:05:13.703+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:05:13.704+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:05:13.704+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:05:13.725+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:05:13.720+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:05:13.726+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:05:13.746+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.047 seconds
[2023-09-05T19:05:44.036+0000] {processor.py:154} INFO - Started process (PID=23603) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:05:44.038+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:05:44.038+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:05:44.038+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:05:44.059+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:05:44.055+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:05:44.062+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:05:44.082+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.049 seconds
[2023-09-05T19:06:14.634+0000] {processor.py:154} INFO - Started process (PID=23671) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:06:14.635+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:06:14.636+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:06:14.636+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:06:14.652+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:06:14.649+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:06:14.653+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:06:14.671+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.039 seconds
[2023-09-05T19:06:45.010+0000] {processor.py:154} INFO - Started process (PID=23745) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:06:45.012+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:06:45.013+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:06:45.012+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:06:45.033+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:06:45.029+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:06:45.035+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:06:45.056+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.049 seconds
[2023-09-05T19:07:15.803+0000] {processor.py:154} INFO - Started process (PID=23819) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:07:15.804+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:07:15.805+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:07:15.805+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:07:15.823+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:07:15.820+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:07:15.825+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:07:15.842+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:07:46.432+0000] {processor.py:154} INFO - Started process (PID=23893) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:07:46.433+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:07:46.434+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:07:46.434+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:07:46.451+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:07:46.447+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:07:46.452+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:07:46.469+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.039 seconds
[2023-09-05T19:08:16.512+0000] {processor.py:154} INFO - Started process (PID=23958) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:08:16.513+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:08:16.514+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:08:16.513+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:08:16.529+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:08:16.527+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:08:16.531+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:08:16.549+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.040 seconds
[2023-09-05T19:08:47.236+0000] {processor.py:154} INFO - Started process (PID=24032) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:08:47.237+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:08:47.238+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:08:47.238+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:08:47.255+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:08:47.252+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:08:47.256+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:08:47.275+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:09:17.771+0000] {processor.py:154} INFO - Started process (PID=24106) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:09:17.772+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:09:17.773+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:09:17.773+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:09:17.790+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:09:17.786+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:09:17.791+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:09:17.809+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.041 seconds
[2023-09-05T19:09:48.558+0000] {processor.py:154} INFO - Started process (PID=24171) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:09:48.559+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:09:48.560+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:09:48.560+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:09:48.578+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:09:48.575+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:09:48.580+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:09:48.600+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:10:19.238+0000] {processor.py:154} INFO - Started process (PID=24245) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:10:19.240+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:10:19.241+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:10:19.241+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:10:19.268+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:10:19.263+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:10:19.271+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:10:19.299+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.067 seconds
[2023-09-05T19:10:49.606+0000] {processor.py:154} INFO - Started process (PID=24319) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:10:49.607+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:10:49.608+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:10:49.608+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:10:49.627+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:10:49.624+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:10:49.629+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:10:49.650+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.047 seconds
[2023-09-05T19:11:20.131+0000] {processor.py:154} INFO - Started process (PID=24393) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:11:20.132+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:11:20.132+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:11:20.132+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:11:20.150+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:11:20.147+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:11:20.151+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:11:20.171+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.043 seconds
[2023-09-05T19:11:50.747+0000] {processor.py:154} INFO - Started process (PID=24458) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:11:50.748+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:11:50.749+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:11:50.749+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:11:50.770+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:11:50.765+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:11:50.772+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:11:50.790+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.046 seconds
[2023-09-05T19:12:21.192+0000] {processor.py:154} INFO - Started process (PID=24533) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:12:21.193+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:12:21.194+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:12:21.193+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:12:21.213+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:12:21.210+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:12:21.215+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:12:21.237+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.048 seconds
[2023-09-05T19:12:51.308+0000] {processor.py:154} INFO - Started process (PID=24607) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:12:51.309+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:12:51.310+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:12:51.309+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:12:51.328+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:12:51.324+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:12:51.330+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:12:51.351+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.046 seconds
[2023-09-05T19:13:22.089+0000] {processor.py:154} INFO - Started process (PID=24681) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:13:22.090+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:13:22.091+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:13:22.091+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:13:22.112+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:13:22.108+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:13:22.114+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:13:22.130+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:13:52.177+0000] {processor.py:154} INFO - Started process (PID=24746) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:13:52.178+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:13:52.179+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:13:52.179+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:13:52.197+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:13:52.193+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:13:52.198+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:13:52.216+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.043 seconds
[2023-09-05T19:14:23.134+0000] {processor.py:154} INFO - Started process (PID=24820) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:14:23.135+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:14:23.136+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:14:23.136+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:14:23.157+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:14:23.152+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:14:23.159+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:14:23.177+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.047 seconds
[2023-09-05T19:14:53.814+0000] {processor.py:154} INFO - Started process (PID=24894) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:14:53.815+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:14:53.815+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:14:53.815+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:14:53.835+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:14:53.831+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:14:53.837+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:14:53.858+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.047 seconds
[2023-09-05T19:15:24.067+0000] {processor.py:154} INFO - Started process (PID=24968) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:15:24.068+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:15:24.068+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:15:24.068+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:15:24.085+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:15:24.082+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:15:24.087+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:15:24.104+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.040 seconds
[2023-09-05T19:15:54.248+0000] {processor.py:154} INFO - Started process (PID=25033) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:15:54.249+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:15:54.250+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:15:54.250+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:15:54.267+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:15:54.264+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:15:54.268+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:15:54.286+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.040 seconds
[2023-09-05T19:16:24.538+0000] {processor.py:154} INFO - Started process (PID=25107) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:16:24.539+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:16:24.540+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:16:24.540+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:16:24.557+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:16:24.554+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:16:24.558+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:16:24.576+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.040 seconds
[2023-09-05T19:16:54.757+0000] {processor.py:154} INFO - Started process (PID=25181) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:16:54.759+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:16:54.759+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:16:54.759+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:16:54.781+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:16:54.776+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:16:54.783+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:16:54.803+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.048 seconds
[2023-09-05T19:17:24.959+0000] {processor.py:154} INFO - Started process (PID=25246) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:17:24.960+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:17:24.960+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:17:24.960+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:17:24.977+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:17:24.974+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:17:24.979+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:17:24.996+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.040 seconds
[2023-09-05T19:17:55.334+0000] {processor.py:154} INFO - Started process (PID=25320) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:17:55.335+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:17:55.336+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:17:55.336+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:17:55.354+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:17:55.350+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:17:55.356+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:17:55.374+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.043 seconds
[2023-09-05T19:18:25.624+0000] {processor.py:154} INFO - Started process (PID=25395) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:18:25.625+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:18:25.626+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:18:25.626+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:18:25.645+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:18:25.641+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:18:25.647+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:18:25.667+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:18:55.883+0000] {processor.py:154} INFO - Started process (PID=25468) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:18:55.884+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:18:55.885+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:18:55.885+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:18:55.906+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:18:55.902+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:18:55.908+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:18:55.928+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.047 seconds
[2023-09-05T19:19:25.985+0000] {processor.py:154} INFO - Started process (PID=25532) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:19:25.987+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:19:25.988+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:19:25.987+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:19:26.008+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:19:26.004+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:19:26.009+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:19:26.029+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.046 seconds
[2023-09-05T19:19:56.795+0000] {processor.py:154} INFO - Started process (PID=25606) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:19:56.796+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:19:56.797+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:19:56.797+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:19:56.817+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:19:56.813+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:19:56.819+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:19:56.839+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.047 seconds
[2023-09-05T19:20:27.351+0000] {processor.py:154} INFO - Started process (PID=25680) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:20:27.352+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:20:27.353+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:20:27.353+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:20:27.372+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:20:27.368+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:20:27.377+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:20:27.397+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.049 seconds
[2023-09-05T19:20:57.534+0000] {processor.py:154} INFO - Started process (PID=25752) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:20:57.535+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:20:57.536+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:20:57.536+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:20:57.553+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:20:57.549+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:20:57.554+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:20:57.573+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:21:27.615+0000] {processor.py:154} INFO - Started process (PID=25819) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:21:27.616+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:21:27.617+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:21:27.617+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:21:27.634+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:21:27.631+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:21:27.635+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:21:27.653+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.041 seconds
[2023-09-05T19:21:57.719+0000] {processor.py:154} INFO - Started process (PID=25893) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:21:57.720+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:21:57.721+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:21:57.721+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:21:57.739+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:21:57.735+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:21:57.740+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:21:57.756+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.039 seconds
[2023-09-05T19:22:27.891+0000] {processor.py:154} INFO - Started process (PID=25966) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:22:27.892+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:22:27.892+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:22:27.892+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:22:27.913+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:22:27.909+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:22:27.914+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:22:27.969+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.081 seconds
[2023-09-05T19:22:58.142+0000] {processor.py:154} INFO - Started process (PID=26031) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:22:58.143+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:22:58.144+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:22:58.143+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:22:58.160+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:22:58.157+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:22:58.162+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:22:58.179+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.040 seconds
[2023-09-05T19:23:28.678+0000] {processor.py:154} INFO - Started process (PID=26106) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:23:28.679+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:23:28.680+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:23:28.680+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:23:28.699+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:23:28.694+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:23:28.700+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:23:28.718+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.043 seconds
[2023-09-05T19:23:59.269+0000] {processor.py:154} INFO - Started process (PID=26180) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:23:59.270+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:23:59.271+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:23:59.271+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:23:59.290+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:23:59.287+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:23:59.291+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:23:59.311+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.047 seconds
[2023-09-05T19:24:29.640+0000] {processor.py:154} INFO - Started process (PID=26254) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:24:29.641+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:24:29.642+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:24:29.642+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:24:29.664+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:24:29.659+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:24:29.666+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:24:29.688+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.052 seconds
[2023-09-05T19:24:59.721+0000] {processor.py:154} INFO - Started process (PID=26319) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:24:59.722+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:24:59.723+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:24:59.723+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:24:59.743+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:24:59.739+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:24:59.744+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:24:59.764+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.046 seconds
[2023-09-05T19:25:30.361+0000] {processor.py:154} INFO - Started process (PID=26393) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:25:30.362+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:25:30.363+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:25:30.363+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:25:30.384+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:25:30.380+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:25:30.386+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:25:30.405+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.048 seconds
[2023-09-05T19:26:00.647+0000] {processor.py:154} INFO - Started process (PID=26467) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:26:00.648+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:26:00.649+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:26:00.648+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:26:00.667+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:26:00.664+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:26:00.669+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:26:00.687+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:26:30.718+0000] {processor.py:154} INFO - Started process (PID=26533) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:26:30.719+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:26:30.720+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:26:30.720+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:26:30.738+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:26:30.735+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:26:30.740+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:26:30.759+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:27:01.015+0000] {processor.py:154} INFO - Started process (PID=26607) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:27:01.016+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:27:01.017+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:27:01.017+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:27:01.038+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:27:01.033+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:27:01.039+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:27:01.059+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.047 seconds
[2023-09-05T19:27:31.368+0000] {processor.py:154} INFO - Started process (PID=26681) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:27:31.370+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:27:31.371+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:27:31.371+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:27:31.395+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:27:31.390+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:27:31.397+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:27:31.424+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.061 seconds
[2023-09-05T19:28:01.515+0000] {processor.py:154} INFO - Started process (PID=26755) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:28:01.517+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:28:01.518+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:28:01.518+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:28:01.540+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:28:01.536+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:28:01.542+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:28:01.564+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.053 seconds
[2023-09-05T19:28:31.637+0000] {processor.py:154} INFO - Started process (PID=26820) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:28:31.638+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:28:31.639+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:28:31.639+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:28:31.657+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:28:31.653+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:28:31.658+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:28:31.675+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.041 seconds
[2023-09-05T19:29:01.807+0000] {processor.py:154} INFO - Started process (PID=26884) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:29:01.808+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:29:01.808+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:29:01.808+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:29:01.831+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:29:01.827+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:29:01.833+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:29:01.852+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.049 seconds
[2023-09-05T19:29:32.046+0000] {processor.py:154} INFO - Started process (PID=26959) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:29:32.047+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:29:32.048+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:29:32.048+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:29:32.066+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:29:32.063+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:29:32.068+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:29:32.087+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:30:02.188+0000] {processor.py:154} INFO - Started process (PID=27023) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:30:02.189+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:30:02.190+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:30:02.189+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:30:02.210+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:30:02.206+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:30:02.212+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:30:02.231+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.046 seconds
[2023-09-05T19:30:32.328+0000] {processor.py:154} INFO - Started process (PID=27098) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:30:32.328+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:30:32.329+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:30:32.329+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:30:32.351+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:30:32.347+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:30:32.352+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:30:32.372+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.047 seconds
[2023-09-05T19:31:03.029+0000] {processor.py:154} INFO - Started process (PID=27167) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:31:03.030+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:31:03.031+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:31:03.031+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:31:03.052+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:31:03.049+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:31:03.054+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:31:03.071+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:31:33.955+0000] {processor.py:154} INFO - Started process (PID=27241) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:31:33.956+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:31:33.956+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:31:33.956+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:31:33.976+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:31:33.973+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:31:33.978+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:31:33.994+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:32:04.434+0000] {processor.py:154} INFO - Started process (PID=27306) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:32:04.435+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:32:04.436+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:32:04.436+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:32:04.458+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:32:04.454+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:32:04.460+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:32:04.478+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.047 seconds
[2023-09-05T19:32:35.023+0000] {processor.py:154} INFO - Started process (PID=27380) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:32:35.024+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:32:35.025+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:32:35.025+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:32:35.045+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:32:35.042+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:32:35.046+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:32:35.063+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:33:05.805+0000] {processor.py:154} INFO - Started process (PID=27454) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:33:05.806+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:33:05.806+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:33:05.806+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:33:05.827+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:33:05.823+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:33:05.828+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:33:05.847+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:33:35.940+0000] {processor.py:154} INFO - Started process (PID=27528) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:33:35.941+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:33:35.941+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:33:35.941+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:33:35.967+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:33:35.961+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:33:35.969+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:33:35.991+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.054 seconds
[2023-09-05T19:34:06.033+0000] {processor.py:154} INFO - Started process (PID=27593) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:34:06.034+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:34:06.035+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:34:06.035+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:34:06.054+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:34:06.050+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:34:06.056+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:34:06.075+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:34:36.936+0000] {processor.py:154} INFO - Started process (PID=27664) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:34:36.937+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:34:36.938+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:34:36.938+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:34:36.962+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:34:36.958+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:34:36.964+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:34:36.986+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.053 seconds
[2023-09-05T19:35:07.799+0000] {processor.py:154} INFO - Started process (PID=27738) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:35:07.800+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:35:07.801+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:35:07.800+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:35:07.822+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:35:07.818+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:35:07.824+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:35:07.840+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:35:38.526+0000] {processor.py:154} INFO - Started process (PID=27812) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:35:38.527+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:35:38.528+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:35:38.528+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:35:38.547+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:35:38.544+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:35:38.548+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:35:38.565+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:36:09.141+0000] {processor.py:154} INFO - Started process (PID=27877) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:36:09.142+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:36:09.142+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:36:09.142+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:36:09.162+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:36:09.159+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:36:09.164+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:36:09.181+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.043 seconds
[2023-09-05T19:36:39.275+0000] {processor.py:154} INFO - Started process (PID=27951) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:36:39.277+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:36:39.277+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:36:39.277+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:36:39.296+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:36:39.293+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:36:39.297+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:36:39.315+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:37:09.806+0000] {processor.py:154} INFO - Started process (PID=28024) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:37:09.807+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:37:09.808+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:37:09.807+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:37:09.829+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:37:09.824+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:37:09.831+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:37:09.848+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:37:39.984+0000] {processor.py:154} INFO - Started process (PID=28096) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:37:39.985+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:37:39.986+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:37:39.986+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:37:40.008+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:37:40.003+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:37:40.010+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:37:40.029+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.048 seconds
[2023-09-05T19:38:10.227+0000] {processor.py:154} INFO - Started process (PID=28158) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:38:10.227+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:38:10.228+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:38:10.228+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:38:10.249+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:38:10.245+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:38:10.250+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:38:10.268+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:38:40.359+0000] {processor.py:154} INFO - Started process (PID=28232) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:38:40.360+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:38:40.361+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:38:40.361+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:38:40.386+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:38:40.382+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:38:40.388+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:38:40.407+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.050 seconds
[2023-09-05T19:39:11.413+0000] {processor.py:154} INFO - Started process (PID=28306) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:39:11.415+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:39:11.415+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:39:11.415+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:39:11.440+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:39:11.437+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:39:11.441+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:39:11.458+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.049 seconds
[2023-09-05T19:39:42.131+0000] {processor.py:154} INFO - Started process (PID=28380) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:39:42.132+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:39:42.133+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:39:42.133+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:39:42.159+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:39:42.154+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:39:42.161+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:39:42.179+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.051 seconds
[2023-09-05T19:40:12.443+0000] {processor.py:154} INFO - Started process (PID=28445) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:40:12.444+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:40:12.445+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:40:12.445+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:40:12.464+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:40:12.461+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:40:12.465+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:40:12.481+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.041 seconds
[2023-09-05T19:40:42.904+0000] {processor.py:154} INFO - Started process (PID=28519) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:40:42.905+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:40:42.906+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:40:42.906+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:40:42.926+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:40:42.923+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:40:42.928+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:40:42.949+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.048 seconds
[2023-09-05T19:41:13.357+0000] {processor.py:154} INFO - Started process (PID=28594) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:41:13.358+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:41:13.359+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:41:13.358+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:41:13.379+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:41:13.375+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:41:13.381+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:41:13.397+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.043 seconds
[2023-09-05T19:41:43.461+0000] {processor.py:154} INFO - Started process (PID=28659) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:41:43.462+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:41:43.463+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:41:43.463+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:41:43.484+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:41:43.481+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:41:43.486+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:41:43.503+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:42:13.841+0000] {processor.py:154} INFO - Started process (PID=28733) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:42:13.842+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:42:13.843+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:42:13.843+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:42:13.862+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:42:13.858+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:42:13.863+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:42:13.881+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:42:44.174+0000] {processor.py:154} INFO - Started process (PID=28807) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:42:44.175+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:42:44.175+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:42:44.175+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:42:44.196+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:42:44.192+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:42:44.197+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:42:44.216+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:43:14.501+0000] {processor.py:154} INFO - Started process (PID=28879) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:43:14.502+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:43:14.503+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:43:14.503+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:43:14.528+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:43:14.522+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:43:14.530+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:43:14.550+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.052 seconds
[2023-09-05T19:43:44.651+0000] {processor.py:154} INFO - Started process (PID=28944) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:43:44.652+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:43:44.653+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:43:44.653+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:43:44.673+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:43:44.668+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:43:44.674+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:43:44.691+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:44:14.902+0000] {processor.py:154} INFO - Started process (PID=29015) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:44:14.903+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:44:14.903+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:44:14.903+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:44:14.925+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:44:14.921+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:44:14.927+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:44:14.943+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.043 seconds
[2023-09-05T19:44:45.804+0000] {processor.py:154} INFO - Started process (PID=29089) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:44:45.805+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:44:45.806+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:44:45.806+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:44:45.827+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:44:45.824+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:44:45.829+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:44:45.845+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:45:16.187+0000] {processor.py:154} INFO - Started process (PID=29154) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:45:16.188+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:45:16.188+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:45:16.188+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:45:16.211+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:45:16.206+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:45:16.213+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:45:16.232+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.050 seconds
[2023-09-05T19:45:46.451+0000] {processor.py:154} INFO - Started process (PID=29228) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:45:46.453+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:45:46.453+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:45:46.453+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:45:46.474+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:45:46.469+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:45:46.475+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:45:46.491+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:46:17.328+0000] {processor.py:154} INFO - Started process (PID=29302) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:46:17.329+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:46:17.330+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:46:17.329+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:46:17.352+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:46:17.348+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:46:17.353+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:46:17.373+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.048 seconds
[2023-09-05T19:46:48.342+0000] {processor.py:154} INFO - Started process (PID=29376) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:46:48.343+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:46:48.343+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:46:48.343+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:46:48.365+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:46:48.362+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:46:48.367+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:46:48.384+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:47:19.025+0000] {processor.py:154} INFO - Started process (PID=29441) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:47:19.026+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:47:19.027+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:47:19.027+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:47:19.049+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:47:19.046+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:47:19.050+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:47:19.067+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:47:49.135+0000] {processor.py:154} INFO - Started process (PID=29515) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:47:49.136+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:47:49.137+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:47:49.137+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:47:49.158+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:47:49.154+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:47:49.160+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:47:49.179+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.046 seconds
[2023-09-05T19:48:19.828+0000] {processor.py:154} INFO - Started process (PID=29589) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:48:19.829+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:48:19.830+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:48:19.830+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:48:19.850+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:48:19.846+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:48:19.851+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:48:19.867+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:48:50.650+0000] {processor.py:154} INFO - Started process (PID=29663) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:48:50.651+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:48:50.652+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:48:50.652+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:48:50.675+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:48:50.671+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:48:50.677+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:48:50.692+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:49:21.152+0000] {processor.py:154} INFO - Started process (PID=29728) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:49:21.153+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:49:21.154+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:49:21.154+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:49:21.175+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:49:21.171+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:49:21.176+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:49:21.193+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:49:51.513+0000] {processor.py:154} INFO - Started process (PID=29802) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:49:51.514+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:49:51.515+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:49:51.515+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:49:51.540+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:49:51.536+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:49:51.542+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:49:51.558+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.048 seconds
[2023-09-05T19:50:22.427+0000] {processor.py:154} INFO - Started process (PID=29876) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:50:22.428+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:50:22.428+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:50:22.428+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:50:22.448+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:50:22.445+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:50:22.450+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:50:22.468+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:50:52.683+0000] {processor.py:154} INFO - Started process (PID=29950) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:50:52.684+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:50:52.685+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:50:52.684+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:50:52.705+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:50:52.701+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:50:52.707+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:50:52.724+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.045 seconds
[2023-09-05T19:51:22.909+0000] {processor.py:154} INFO - Started process (PID=30015) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:51:22.910+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:51:22.911+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:51:22.911+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:51:22.932+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:51:22.929+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:51:22.934+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:51:22.952+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.046 seconds
[2023-09-05T19:51:53.708+0000] {processor.py:154} INFO - Started process (PID=30089) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:51:53.709+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:51:53.710+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:51:53.710+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:51:53.728+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:51:53.725+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:51:53.729+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:51:53.746+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.041 seconds
[2023-09-05T19:52:23.837+0000] {processor.py:154} INFO - Started process (PID=30163) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:52:23.838+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:52:23.838+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:52:23.838+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:52:23.858+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:52:23.854+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:52:23.859+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:52:23.877+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:52:54.136+0000] {processor.py:154} INFO - Started process (PID=30234) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:52:54.137+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:52:54.138+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:52:54.138+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:52:54.159+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:52:54.154+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:52:54.160+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:52:54.179+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.046 seconds
[2023-09-05T19:53:24.603+0000] {processor.py:154} INFO - Started process (PID=30299) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:53:24.604+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:53:24.604+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:53:24.604+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:53:24.639+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:53:24.634+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:53:24.640+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:53:24.660+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.062 seconds
[2023-09-05T19:53:55.270+0000] {processor.py:154} INFO - Started process (PID=30373) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:53:55.271+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:53:55.272+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:53:55.272+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:53:55.291+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:53:55.287+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:53:55.292+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:53:55.309+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.041 seconds
[2023-09-05T19:54:25.930+0000] {processor.py:154} INFO - Started process (PID=30447) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:54:25.932+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:54:25.933+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:54:25.932+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:54:25.953+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:54:25.949+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:54:25.954+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:54:25.970+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:54:56.065+0000] {processor.py:154} INFO - Started process (PID=30521) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:54:56.066+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:54:56.067+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:54:56.067+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:54:56.089+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:54:56.085+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:54:56.091+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:54:56.112+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.050 seconds
[2023-09-05T19:55:26.338+0000] {processor.py:154} INFO - Started process (PID=30586) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:55:26.339+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:55:26.340+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:55:26.340+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:55:26.363+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:55:26.359+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:55:26.365+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:55:26.385+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.049 seconds
[2023-09-05T19:55:56.421+0000] {processor.py:154} INFO - Started process (PID=30661) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:55:56.422+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:55:56.423+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:55:56.422+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:55:56.439+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:55:56.435+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:55:56.440+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:55:56.456+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.038 seconds
[2023-09-05T19:56:26.571+0000] {processor.py:154} INFO - Started process (PID=30735) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:56:26.572+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:56:26.573+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:56:26.573+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:56:26.591+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:56:26.588+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:56:26.592+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:56:26.610+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:56:57.093+0000] {processor.py:154} INFO - Started process (PID=30797) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:56:57.094+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:56:57.095+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:56:57.094+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:56:57.114+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:56:57.110+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:56:57.116+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:56:57.135+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.044 seconds
[2023-09-05T19:57:27.663+0000] {processor.py:154} INFO - Started process (PID=30871) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:57:27.664+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:57:27.664+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:57:27.664+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:57:27.684+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:57:27.681+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:57:27.685+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:57:27.702+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:57:57.752+0000] {processor.py:154} INFO - Started process (PID=30945) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:57:57.753+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:57:57.754+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:57:57.754+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:57:57.773+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:57:57.769+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:57:57.774+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:57:57.792+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.042 seconds
[2023-09-05T19:58:27.874+0000] {processor.py:154} INFO - Started process (PID=31010) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:58:27.876+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:58:27.878+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:58:27.878+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:58:27.919+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:58:27.912+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:58:27.921+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:58:27.956+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.088 seconds
[2023-09-05T19:58:58.215+0000] {processor.py:154} INFO - Started process (PID=31085) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:58:58.217+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:58:58.218+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:58:58.218+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:58:58.261+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:58:58.254+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:58:58.264+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:58:58.293+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.082 seconds
[2023-09-05T19:59:28.945+0000] {processor.py:154} INFO - Started process (PID=31158) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:59:28.946+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:59:28.947+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:59:28.947+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:59:28.984+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:59:28.977+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:59:28.986+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:59:29.014+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.073 seconds
[2023-09-05T19:59:59.159+0000] {processor.py:154} INFO - Started process (PID=31224) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:59:59.161+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T19:59:59.163+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:59:59.163+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:59:59.200+0000] {logging_mixin.py:120} INFO - [2023-09-05T19:59:59.194+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T19:59:59.202+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T19:59:59.233+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.077 seconds
[2023-09-05T20:00:29.367+0000] {processor.py:154} INFO - Started process (PID=31298) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:00:29.368+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:00:29.369+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:00:29.369+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:00:29.409+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:00:29.402+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:00:29.412+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:00:29.448+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.086 seconds
[2023-09-05T20:01:00.122+0000] {processor.py:154} INFO - Started process (PID=31363) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:01:00.123+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:01:00.125+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:01:00.125+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:01:00.161+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:01:00.154+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:01:00.163+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:01:00.196+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.078 seconds
[2023-09-05T20:01:30.865+0000] {processor.py:154} INFO - Started process (PID=31438) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:01:30.866+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:01:30.868+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:01:30.868+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:01:30.908+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:01:30.898+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:01:30.912+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:01:30.941+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.080 seconds
[2023-09-05T20:02:01.446+0000] {processor.py:154} INFO - Started process (PID=31503) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:02:01.448+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:02:01.449+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:02:01.449+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:02:01.482+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:02:01.474+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:02:01.484+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:02:01.515+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.073 seconds
[2023-09-05T20:02:31.979+0000] {processor.py:154} INFO - Started process (PID=31579) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:02:31.981+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:02:31.982+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:02:31.982+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:02:32.017+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:02:32.011+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:02:32.020+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:02:32.047+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.073 seconds
[2023-09-05T20:03:02.203+0000] {processor.py:154} INFO - Started process (PID=31643) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:03:02.205+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:03:02.207+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:03:02.207+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:03:02.269+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:03:02.258+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:03:02.273+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:03:02.309+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.113 seconds
[2023-09-05T20:03:32.532+0000] {processor.py:154} INFO - Started process (PID=31717) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:03:32.534+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:03:32.535+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:03:32.535+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:03:32.576+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:03:32.569+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:03:32.578+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:03:32.611+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.083 seconds
[2023-09-05T20:04:03.293+0000] {processor.py:154} INFO - Started process (PID=31792) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:04:03.295+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:04:03.297+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:04:03.296+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:04:03.335+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:04:03.329+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:04:03.337+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:04:03.367+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.080 seconds
[2023-09-05T20:04:33.638+0000] {processor.py:154} INFO - Started process (PID=31857) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:04:33.639+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:04:33.640+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:04:33.640+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:04:33.672+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:04:33.667+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:04:33.674+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:04:33.706+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.073 seconds
[2023-09-05T20:05:03.960+0000] {processor.py:154} INFO - Started process (PID=31932) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:05:03.962+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:05:03.963+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:05:03.963+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:05:04.007+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:05:04.001+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:05:04.009+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:05:04.038+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.085 seconds
[2023-09-05T20:05:34.647+0000] {processor.py:154} INFO - Started process (PID=31997) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:05:34.648+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:05:34.649+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:05:34.649+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:05:34.687+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:05:34.681+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:05:34.691+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:05:34.718+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.075 seconds
[2023-09-05T20:06:05.098+0000] {processor.py:154} INFO - Started process (PID=32071) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:06:05.101+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:06:05.102+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:06:05.102+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:06:05.162+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:06:05.150+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:06:05.167+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:06:05.195+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.103 seconds
[2023-09-05T20:06:35.374+0000] {processor.py:154} INFO - Started process (PID=32136) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:06:35.376+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:06:35.377+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:06:35.377+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:06:35.422+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:06:35.414+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:06:35.425+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:06:35.463+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.096 seconds
[2023-09-05T20:07:05.777+0000] {processor.py:154} INFO - Started process (PID=32210) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:07:05.779+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:07:05.780+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:07:05.780+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:07:05.823+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:07:05.816+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:07:05.827+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:07:05.863+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.090 seconds
[2023-09-05T20:07:36.659+0000] {processor.py:154} INFO - Started process (PID=32275) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:07:36.662+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:07:36.664+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:07:36.664+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:07:36.708+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:07:36.700+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:07:36.712+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:07:36.753+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.103 seconds
[2023-09-05T20:08:06.959+0000] {processor.py:154} INFO - Started process (PID=32349) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:08:06.961+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:08:06.962+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:08:06.962+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:08:07.008+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:08:07.001+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:08:07.011+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:08:07.044+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.092 seconds
[2023-09-05T20:08:37.446+0000] {processor.py:154} INFO - Started process (PID=32414) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:08:37.448+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-05T20:08:37.449+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:08:37.449+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:08:37.497+0000] {logging_mixin.py:120} INFO - [2023-09-05T20:08:37.487+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task.group import TaskGroup
ModuleNotFoundError: No module named 'airflow.utils.task'
[2023-09-05T20:08:37.500+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-05T20:08:37.537+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.095 seconds
